name: try_flutter
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  mqtt_client: ^10.2.1
  flutter_svg: ^2.0.10+1
  english_words: ^4.0.0
  provider: ^6.0.0
  googleapis: ^13.1.0
  googleapis_auth: ^1.3.0
  http: ^1.0.0
  flutter_secure_storage: ^9.2.2
  fl_chart: ^0.68.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

assets:
  - web/icons/waterdrop.png
  - assets/service_account.json

  